name: "Setup"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "me@enji.dev"
        git config --global user.name "enjidev"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
