packages:
  - packages/*
  - internal/*
  - apps/storybook/*
  - apps/*

catalog:
  "@ark-ui/react": ^5.35.0
  "@ark-ui/vue": ^5.35.0
  "@changesets/changelog-github": ^0.6.0
  "@changesets/cli": ^2.30.0
  "@commitlint/cli": ^20.5.0
  "@commitlint/config-conventional": ^20.5.0
  "@stark-loader/react": ^0.3.0
  "@tailwindcss/postcss": ^4.2.2
  "@tailwindcss/vite": ^4.2.2
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@testing-library/vue": ^8.1.0
  "@types/node": ^25.5.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^2.0.1
  "@vercel/speed-insights": ^2.0.0
  "@vitejs/plugin-react": ^6.0.1
  "@vitejs/plugin-vue": ^6.0.5
  "@vueuse/core": ^14.2.1
  clsx: ^2.1.1
  husky: ^9.1.7
  jsdom: ^29.0.2
  lint-staged: ^16.4.0
  lucide-react: ^1.7.0
  next: ^16.2.2
  next-themes: ^0.4.6
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  react: ^19.2.4
  react-dom: ^19.2.4
  react-icons: ^5.6.0
  rollup-preserve-directives: ^1.1.3
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.2.2
  typescript: ^6.0.2
  ultracite: ^7.4.3
  vite: ^8.0.7
  vite-plugin-dts: ^4.5.4
  vitest: ^4.1.3
  vue: ^3.5.32
  vue-tsc: ^3.2.6

catalogs:
  storybook:
    "@storybook/addon-a11y": ^10.3.5
    "@storybook/addon-themes": ^10.3.5
    "@storybook/react-vite": ^10.3.5
    "@storybook/vue3-vite": ^10.3.5
    storybook: ^10.3.5

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
